baseURL = "http://www.tcsh.org/"
languageCode = "en-us"
title = "TCSH"
theme = "xmin"
publishDir = "docs"
enableGitInfo = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Mailing list"
    url = "https://mailman.astron.com/mailman/listinfo/tcsh"

[[menu.main]]
    name = "Source"
    url = "https://github.com/tcsh-org/tcsh"
