baseURL = "http://www.tcsh.org/"
languageCode = "en-us"
title = "TCSH"
theme = "xmin"
publishDir = "docs"
enableGitInfo = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
